version: '3.8'

services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0.3
    container_name: zabbix-proxy
    restart: always
    environment:
      - ZBX_DB_HOST=${ZBX_DB_HOST}
      - ZBX_DB_NAME=${ZBX_DB_NAME}
      - ZBX_DB_USER=${ZBX_DB_USER}
      - ZBX_DB_PASSWORD=${ZBX_DB_PASSWORD}
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_LISTEN_IP=${ZBX_LISTEN_IP}
      - ZBX_LISTEN_PORT=${ZBX_LISTEN_PORT}
      - ZBX_LOG_FILE=${ZBX_LOG_FILE}
      - ZBX_PSK_IDENTITY=${ZBX_PSK_IDENTITY}
      - ZBX_PSK=${ZBX_PSK}
      - ZBX_ENABLEREMOTECOMMANDS=${ZBX_ENABLEREMOTECOMMANDS}
      - ZBX_LOGREMOTECOMMANDS=${ZBX_LOGREMOTECOMMANDS}
      - ZBX_SOURCEIP=${ZBX_SOURCEIP}
      - ZBX_HOSTNAMEITEM=${ZBX_HOSTNAMEITEM}
      - ZBX_PROXYLOCALBUFFER=${ZBX_PROXYLOCALBUFFER}
      - ZBX_PROXYOFFLINEBUFFER=${ZBX_PROXYOFFLINEBUFFER}
      - ZBX_PROXYHEARTBEATFREQUENCY=${ZBX_PROXYHEARTBEATFREQUENCY}
      - ZBX_CONFIGFREQUENCY=${ZBX_CONFIGFREQUENCY}
      - ZBX_PROXYCONFIGFREQUENCY=${ZBX_PROXYCONFIGFREQUENCY}
      - ZBX_DATASENDERFREQUENCY=${ZBX_DATASENDERFREQUENCY}
      - ZBX_STARTPOLLERS=${ZBX_STARTPOLLERS}
      - ZBX_STARTPREPROCESSORS=${ZBX_STARTPREPROCESSORS}
      - ZBX_STARTIPMIPOLLERS=${ZBX_STARTIPMIPOLLERS}
      - ZBX_STARTPOLLERSUNREACHABLE=${ZBX_STARTPOLLERSUNREACHABLE}
      - ZBX_STARTTRAPPERS=${ZBX_STARTTRAPPERS}
      - ZBX_STARTPINGERS=${ZBX_STARTPINGERS}
      - ZBX_STARTDISCOVERERS=${ZBX_STARTDISCOVERERS}
      - ZBX_STARTHISTORYPOLLERS=${ZBX_STARTHISTORYPOLLERS}
      - ZBX_STARTHTTPPOLLERS=${ZBX_STARTHTTPPOLLERS}
      - ZBX_STARTODBCPOLLERS=${ZBX_STARTODBCPOLLERS}
      - ZBX_JAVAGATEWAY=${ZBX_JAVAGATEWAY}
      - ZBX_JAVAGATEWAYPORT=${ZBX_JAVAGATEWAYPORT}
      - ZBX_STARTJAVAPOLLERS=${ZBX_STARTJAVAPOLLERS}
      - ZBX_STATSALLOWEDIP=${ZBX_STATSALLOWEDIP}
      - ZBX_STARTVMWARECOLLECTORS=${ZBX_STARTVMWARECOLLECTORS}
      - ZBX_VMWAREFREQUENCY=${ZBX_VMWAREFREQUENCY}
      - ZBX_VMWAREPERFFREQUENCY=${ZBX_VMWAREPERFFREQUENCY}
      - ZBX_VMWARECACHESIZE=${ZBX_VMWARECACHESIZE}
      - ZBX_VMWARETIMEOUT=${ZBX_VMWARETIMEOUT}
      - ZBX_ENABLE_SNMP_TRAPS=${ZBX_ENABLE_SNMP_TRAPS}
      - ZBX_LISTENIP=${ZBX_LISTENIP}
      - ZBX_LISTENPORT=${ZBX_LISTENPORT}
      - ZBX_LISTENBACKLOG=${ZBX_LISTENBACKLOG}
      - ZBX_HOUSEKEEPINGFREQUENCY=${ZBX_HOUSEKEEPINGFREQUENCY}
      - ZBX_CACHESIZE=${ZBX_CACHESIZE}
      - ZBX_STARTDBSYNCERS=${ZBX_STARTDBSYNCERS}
      - ZBX_HISTORYCACHESIZE=${ZBX_HISTORYCACHESIZE}
      - ZBX_HISTORYINDEXCACHESIZE=${ZBX_HISTORYINDEXCACHESIZE}
      - ZBX_TRAPPERTIMEOUT=${ZBX_TRAPPERTIMEOUT}
      - ZBX_UNREACHABLEPERIOD=${ZBX_UNREACHABLEPERIOD}
      - ZBX_UNAVAILABLEDELAY=${ZBX_UNAVAILABLEDELAY}
      - ZBX_UNREACHABLEDELAY=${ZBX_UNREACHABLEDELAY}
      - ZBX_LOGSLOWQUERIES=${ZBX_LOGSLOWQUERIES}
      - ZBX_TLSCONNECT=${ZBX_TLSCONNECT}
      - ZBX_TLSACCEPT=${ZBX_TLSACCEPT}
      - ZBX_TLSCAFILE=${ZBX_TLSCAFILE}
      - ZBX_TLSCA=${ZBX_TLSCA}
      - ZBX_TLSCRLFILE=${ZBX_TLSCRLFILE}
      - ZBX_TLSCRL=${ZBX_TLSCRL}
      - ZBX_TLSSERVERCERTISSUER=${ZBX_TLSSERVERCERTISSUER}
      - ZBX_TLSSERVERCERTSUBJECT=${ZBX_TLSSERVERCERTSUBJECT}
      - ZBX_TLSCERTFILE=${ZBX_TLSCERTFILE}
      - ZBX_TLSCERT=${ZBX_TLSCERT}
      - ZBX_TLSKEYFILE=${ZBX_TLSKEYFILE}
      - ZBX_TLSKEY=${ZBX_TLSKEY}
      - ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY}
      - ZBX_TLSPSKFILE=${ZBX_TLSPSKFILE}
      - ZBX_TLSPSK=${ZBX_TLSPSK}
      - ZBX_TLSCIPHERALL=${ZBX_TLSCIPHERALL}
      - ZBX_TLSCIPHERALL13=${ZBX_TLSCIPHERALL13}
      - ZBX_TLSCIPHERCERT=${ZBX_TLSCIPHERCERT}
      - ZBX_TLSCIPHERCERT13=${ZBX_TLSCIPHERCERT13}
      - ZBX_TLSCIPHERPSK=${ZBX_TLSCIPHERPSK}
      - ZBX_TLSCIPHERPSK13=${ZBX_TLSCIPHERPSK13}
      - ZBX_WEBDRIVERURL=${ZBX_WEBDRIVERURL}
      - ZBX_STARTBROWSERPOLLERS=${ZBX_STARTBROWSERPOLLERS}
    volumes:
      - ./data/zabbix_proxy:/var/lib/zabbix/db_data
      - ./zabbix:/etc/zabbix  # Монтируем папку с конфигами
    ports:
      - "${ZBX_LISTEN_PORT}:${ZBX_LISTEN_PORT}"
    networks:
      - zabbix_net

networks:
  zabbix_net:
    driver: bridge
